// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package com.tmindtech.api.model.protobuf;

public final class ExampleProtos {
  private ExampleProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tmindtech.protobuf.example.Example)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 3;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string extras = 4;</code>
     */
    java.lang.String getExtras();
    /**
     * <code>string extras = 4;</code>
     */
    com.google.protobuf.ByteString
        getExtrasBytes();

    /**
     * <code>.google.protobuf.Timestamp create_time = 5;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>.google.protobuf.Timestamp create_time = 5;</code>
     */
    com.google.protobuf.Timestamp getCreateTime();
    /**
     * <code>.google.protobuf.Timestamp create_time = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp modify_time = 6;</code>
     */
    boolean hasModifyTime();
    /**
     * <code>.google.protobuf.Timestamp modify_time = 6;</code>
     */
    com.google.protobuf.Timestamp getModifyTime();
    /**
     * <code>.google.protobuf.Timestamp modify_time = 6;</code>
     */
    com.google.protobuf.TimestampOrBuilder getModifyTimeOrBuilder();
  }
  /**
   * Protobuf type {@code tmindtech.protobuf.example.Example}
   */
  public  static final class Example extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tmindtech.protobuf.example.Example)
      ExampleOrBuilder {
    // Use Example.newBuilder() to construct.
    private Example(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Example() {
      id_ = 0L;
      name_ = "";
      description_ = "";
      extras_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_Example_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_Example_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tmindtech.api.model.protobuf.ExampleProtos.Example.class, com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 3;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRAS_FIELD_NUMBER = 4;
    private volatile java.lang.Object extras_;
    /**
     * <code>string extras = 4;</code>
     */
    public java.lang.String getExtras() {
      java.lang.Object ref = extras_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extras_ = s;
        return s;
      }
    }
    /**
     * <code>string extras = 4;</code>
     */
    public com.google.protobuf.ByteString
        getExtrasBytes() {
      java.lang.Object ref = extras_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extras_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp createTime_;
    /**
     * <code>.google.protobuf.Timestamp create_time = 5;</code>
     */
    public boolean hasCreateTime() {
      return createTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 5;</code>
     */
    public com.google.protobuf.Timestamp getCreateTime() {
      return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      return getCreateTime();
    }

    public static final int MODIFY_TIME_FIELD_NUMBER = 6;
    private com.google.protobuf.Timestamp modifyTime_;
    /**
     * <code>.google.protobuf.Timestamp modify_time = 6;</code>
     */
    public boolean hasModifyTime() {
      return modifyTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp modify_time = 6;</code>
     */
    public com.google.protobuf.Timestamp getModifyTime() {
      return modifyTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modifyTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp modify_time = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getModifyTimeOrBuilder() {
      return getModifyTime();
    }

    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tmindtech.api.model.protobuf.ExampleProtos.Example prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tmindtech.protobuf.example.Example}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tmindtech.protobuf.example.Example)
        com.tmindtech.api.model.protobuf.ExampleProtos.ExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_Example_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_Example_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tmindtech.api.model.protobuf.ExampleProtos.Example.class, com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder.class);
      }

      // Construct using com.tmindtech.api.model.protobuf.ExampleProtos.Example.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        description_ = "";

        extras_ = "";

        if (createTimeBuilder_ == null) {
          createTime_ = null;
        } else {
          createTime_ = null;
          createTimeBuilder_ = null;
        }
        if (modifyTimeBuilder_ == null) {
          modifyTime_ = null;
        } else {
          modifyTime_ = null;
          modifyTimeBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_Example_descriptor;
      }

      public com.tmindtech.api.model.protobuf.ExampleProtos.Example getDefaultInstanceForType() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.Example.getDefaultInstance();
      }

      public com.tmindtech.api.model.protobuf.ExampleProtos.Example build() {
        com.tmindtech.api.model.protobuf.ExampleProtos.Example result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tmindtech.api.model.protobuf.ExampleProtos.Example buildPartial() {
        com.tmindtech.api.model.protobuf.ExampleProtos.Example result = new com.tmindtech.api.model.protobuf.ExampleProtos.Example(this);
        result.id_ = id_;
        result.name_ = name_;
        result.description_ = description_;
        result.extras_ = extras_;
        if (createTimeBuilder_ == null) {
          result.createTime_ = createTime_;
        } else {
          result.createTime_ = createTimeBuilder_.build();
        }
        if (modifyTimeBuilder_ == null) {
          result.modifyTime_ = modifyTime_;
        } else {
          result.modifyTime_ = modifyTimeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object extras_ = "";
      /**
       * <code>string extras = 4;</code>
       */
      public java.lang.String getExtras() {
        java.lang.Object ref = extras_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extras_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string extras = 4;</code>
       */
      public com.google.protobuf.ByteString
          getExtrasBytes() {
        java.lang.Object ref = extras_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extras_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extras = 4;</code>
       */
      public Builder setExtras(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extras_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extras = 4;</code>
       */
      public Builder clearExtras() {
        
        extras_ = getDefaultInstance().getExtras();
        onChanged();
        return this;
      }
      /**
       * <code>string extras = 4;</code>
       */
      public Builder setExtrasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extras_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createTime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp create_time = 5;</code>
       */
      public boolean hasCreateTime() {
        return createTimeBuilder_ != null || createTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 5;</code>
       */
      public com.google.protobuf.Timestamp getCreateTime() {
        if (createTimeBuilder_ == null) {
          return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
        } else {
          return createTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 5;</code>
       */
      public Builder setCreateTime(com.google.protobuf.Timestamp value) {
        if (createTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createTime_ = value;
          onChanged();
        } else {
          createTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 5;</code>
       */
      public Builder setCreateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createTimeBuilder_ == null) {
          createTime_ = builderForValue.build();
          onChanged();
        } else {
          createTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 5;</code>
       */
      public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
        if (createTimeBuilder_ == null) {
          if (createTime_ != null) {
            createTime_ =
              com.google.protobuf.Timestamp.newBuilder(createTime_).mergeFrom(value).buildPartial();
          } else {
            createTime_ = value;
          }
          onChanged();
        } else {
          createTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 5;</code>
       */
      public Builder clearCreateTime() {
        if (createTimeBuilder_ == null) {
          createTime_ = null;
          onChanged();
        } else {
          createTime_ = null;
          createTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
        
        onChanged();
        return getCreateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
        if (createTimeBuilder_ != null) {
          return createTimeBuilder_.getMessageOrBuilder();
        } else {
          return createTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreateTimeFieldBuilder() {
        if (createTimeBuilder_ == null) {
          createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreateTime(),
                  getParentForChildren(),
                  isClean());
          createTime_ = null;
        }
        return createTimeBuilder_;
      }

      private com.google.protobuf.Timestamp modifyTime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> modifyTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp modify_time = 6;</code>
       */
      public boolean hasModifyTime() {
        return modifyTimeBuilder_ != null || modifyTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp modify_time = 6;</code>
       */
      public com.google.protobuf.Timestamp getModifyTime() {
        if (modifyTimeBuilder_ == null) {
          return modifyTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modifyTime_;
        } else {
          return modifyTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp modify_time = 6;</code>
       */
      public Builder setModifyTime(com.google.protobuf.Timestamp value) {
        if (modifyTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          modifyTime_ = value;
          onChanged();
        } else {
          modifyTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp modify_time = 6;</code>
       */
      public Builder setModifyTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (modifyTimeBuilder_ == null) {
          modifyTime_ = builderForValue.build();
          onChanged();
        } else {
          modifyTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp modify_time = 6;</code>
       */
      public Builder mergeModifyTime(com.google.protobuf.Timestamp value) {
        if (modifyTimeBuilder_ == null) {
          if (modifyTime_ != null) {
            modifyTime_ =
              com.google.protobuf.Timestamp.newBuilder(modifyTime_).mergeFrom(value).buildPartial();
          } else {
            modifyTime_ = value;
          }
          onChanged();
        } else {
          modifyTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp modify_time = 6;</code>
       */
      public Builder clearModifyTime() {
        if (modifyTimeBuilder_ == null) {
          modifyTime_ = null;
          onChanged();
        } else {
          modifyTime_ = null;
          modifyTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp modify_time = 6;</code>
       */
      public com.google.protobuf.Timestamp.Builder getModifyTimeBuilder() {
        
        onChanged();
        return getModifyTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp modify_time = 6;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getModifyTimeOrBuilder() {
        if (modifyTimeBuilder_ != null) {
          return modifyTimeBuilder_.getMessageOrBuilder();
        } else {
          return modifyTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : modifyTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp modify_time = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getModifyTimeFieldBuilder() {
        if (modifyTimeBuilder_ == null) {
          modifyTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getModifyTime(),
                  getParentForChildren(),
                  isClean());
          modifyTime_ = null;
        }
        return modifyTimeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tmindtech.protobuf.example.Example)
    }

    // @@protoc_insertion_point(class_scope:tmindtech.protobuf.example.Example)
    private static final com.tmindtech.api.model.protobuf.ExampleProtos.Example DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tmindtech.api.model.protobuf.ExampleProtos.Example();
    }

    public static com.tmindtech.api.model.protobuf.ExampleProtos.Example getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Example>
        PARSER = new com.google.protobuf.AbstractParser<Example>() {
      public Example parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Example> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Example> getParserForType() {
      return PARSER;
    }

    public com.tmindtech.api.model.protobuf.ExampleProtos.Example getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExampleListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tmindtech.protobuf.example.ExampleList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 offset = 1;</code>
     */
    int getOffset();

    /**
     * <code>int32 count = 2;</code>
     */
    int getCount();

    /**
     * <code>int32 total_count = 3;</code>
     */
    int getTotalCount();

    /**
     * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
     */
    java.util.List<com.tmindtech.api.model.protobuf.ExampleProtos.Example> 
        getExamplesList();
    /**
     * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
     */
    com.tmindtech.api.model.protobuf.ExampleProtos.Example getExamples(int index);
    /**
     * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
     */
    int getExamplesCount();
    /**
     * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
     */
    java.util.List<? extends com.tmindtech.api.model.protobuf.ExampleProtos.ExampleOrBuilder> 
        getExamplesOrBuilderList();
    /**
     * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
     */
    com.tmindtech.api.model.protobuf.ExampleProtos.ExampleOrBuilder getExamplesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tmindtech.protobuf.example.ExampleList}
   */
  public  static final class ExampleList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tmindtech.protobuf.example.ExampleList)
      ExampleListOrBuilder {
    // Use ExampleList.newBuilder() to construct.
    private ExampleList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExampleList() {
      offset_ = 0;
      count_ = 0;
      totalCount_ = 0;
      examples_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_ExampleList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_ExampleList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList.class, com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList.Builder.class);
    }

    private int bitField0_;
    public static final int OFFSET_FIELD_NUMBER = 1;
    private int offset_;
    /**
     * <code>int32 offset = 1;</code>
     */
    public int getOffset() {
      return offset_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    public static final int TOTAL_COUNT_FIELD_NUMBER = 3;
    private int totalCount_;
    /**
     * <code>int32 total_count = 3;</code>
     */
    public int getTotalCount() {
      return totalCount_;
    }

    public static final int EXAMPLES_FIELD_NUMBER = 4;
    private java.util.List<com.tmindtech.api.model.protobuf.ExampleProtos.Example> examples_;
    /**
     * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
     */
    public java.util.List<com.tmindtech.api.model.protobuf.ExampleProtos.Example> getExamplesList() {
      return examples_;
    }
    /**
     * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
     */
    public java.util.List<? extends com.tmindtech.api.model.protobuf.ExampleProtos.ExampleOrBuilder> 
        getExamplesOrBuilderList() {
      return examples_;
    }
    /**
     * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
     */
    public int getExamplesCount() {
      return examples_.size();
    }
    /**
     * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
     */
    public com.tmindtech.api.model.protobuf.ExampleProtos.Example getExamples(int index) {
      return examples_.get(index);
    }
    /**
     * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
     */
    public com.tmindtech.api.model.protobuf.ExampleProtos.ExampleOrBuilder getExamplesOrBuilder(
        int index) {
      return examples_.get(index);
    }

    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tmindtech.protobuf.example.ExampleList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tmindtech.protobuf.example.ExampleList)
        com.tmindtech.api.model.protobuf.ExampleProtos.ExampleListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_ExampleList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_ExampleList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList.class, com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList.Builder.class);
      }

      // Construct using com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getExamplesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        offset_ = 0;

        count_ = 0;

        totalCount_ = 0;

        if (examplesBuilder_ == null) {
          examples_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          examplesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_ExampleList_descriptor;
      }

      public com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList getDefaultInstanceForType() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList.getDefaultInstance();
      }

      public com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList build() {
        com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList buildPartial() {
        com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList result = new com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.offset_ = offset_;
        result.count_ = count_;
        result.totalCount_ = totalCount_;
        if (examplesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            examples_ = java.util.Collections.unmodifiableList(examples_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.examples_ = examples_;
        } else {
          result.examples_ = examplesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      private int bitField0_;

      private int offset_ ;
      /**
       * <code>int32 offset = 1;</code>
       */
      public int getOffset() {
        return offset_;
      }
      /**
       * <code>int32 offset = 1;</code>
       */
      public Builder setOffset(int value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 offset = 1;</code>
       */
      public Builder clearOffset() {
        
        offset_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 2;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private int totalCount_ ;
      /**
       * <code>int32 total_count = 3;</code>
       */
      public int getTotalCount() {
        return totalCount_;
      }
      /**
       * <code>int32 total_count = 3;</code>
       */
      public Builder setTotalCount(int value) {
        
        totalCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 total_count = 3;</code>
       */
      public Builder clearTotalCount() {
        
        totalCount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.tmindtech.api.model.protobuf.ExampleProtos.Example> examples_ =
        java.util.Collections.emptyList();
      private void ensureExamplesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          examples_ = new java.util.ArrayList<com.tmindtech.api.model.protobuf.ExampleProtos.Example>(examples_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tmindtech.api.model.protobuf.ExampleProtos.Example, com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder, com.tmindtech.api.model.protobuf.ExampleProtos.ExampleOrBuilder> examplesBuilder_;

      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public java.util.List<com.tmindtech.api.model.protobuf.ExampleProtos.Example> getExamplesList() {
        if (examplesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(examples_);
        } else {
          return examplesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public int getExamplesCount() {
        if (examplesBuilder_ == null) {
          return examples_.size();
        } else {
          return examplesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public com.tmindtech.api.model.protobuf.ExampleProtos.Example getExamples(int index) {
        if (examplesBuilder_ == null) {
          return examples_.get(index);
        } else {
          return examplesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public Builder setExamples(
          int index, com.tmindtech.api.model.protobuf.ExampleProtos.Example value) {
        if (examplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExamplesIsMutable();
          examples_.set(index, value);
          onChanged();
        } else {
          examplesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public Builder setExamples(
          int index, com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder builderForValue) {
        if (examplesBuilder_ == null) {
          ensureExamplesIsMutable();
          examples_.set(index, builderForValue.build());
          onChanged();
        } else {
          examplesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public Builder addExamples(com.tmindtech.api.model.protobuf.ExampleProtos.Example value) {
        if (examplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExamplesIsMutable();
          examples_.add(value);
          onChanged();
        } else {
          examplesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public Builder addExamples(
          int index, com.tmindtech.api.model.protobuf.ExampleProtos.Example value) {
        if (examplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureExamplesIsMutable();
          examples_.add(index, value);
          onChanged();
        } else {
          examplesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public Builder addExamples(
          com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder builderForValue) {
        if (examplesBuilder_ == null) {
          ensureExamplesIsMutable();
          examples_.add(builderForValue.build());
          onChanged();
        } else {
          examplesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public Builder addExamples(
          int index, com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder builderForValue) {
        if (examplesBuilder_ == null) {
          ensureExamplesIsMutable();
          examples_.add(index, builderForValue.build());
          onChanged();
        } else {
          examplesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public Builder addAllExamples(
          java.lang.Iterable<? extends com.tmindtech.api.model.protobuf.ExampleProtos.Example> values) {
        if (examplesBuilder_ == null) {
          ensureExamplesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, examples_);
          onChanged();
        } else {
          examplesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public Builder clearExamples() {
        if (examplesBuilder_ == null) {
          examples_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          examplesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public Builder removeExamples(int index) {
        if (examplesBuilder_ == null) {
          ensureExamplesIsMutable();
          examples_.remove(index);
          onChanged();
        } else {
          examplesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder getExamplesBuilder(
          int index) {
        return getExamplesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public com.tmindtech.api.model.protobuf.ExampleProtos.ExampleOrBuilder getExamplesOrBuilder(
          int index) {
        if (examplesBuilder_ == null) {
          return examples_.get(index);  } else {
          return examplesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public java.util.List<? extends com.tmindtech.api.model.protobuf.ExampleProtos.ExampleOrBuilder> 
           getExamplesOrBuilderList() {
        if (examplesBuilder_ != null) {
          return examplesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(examples_);
        }
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder addExamplesBuilder() {
        return getExamplesFieldBuilder().addBuilder(
            com.tmindtech.api.model.protobuf.ExampleProtos.Example.getDefaultInstance());
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder addExamplesBuilder(
          int index) {
        return getExamplesFieldBuilder().addBuilder(
            index, com.tmindtech.api.model.protobuf.ExampleProtos.Example.getDefaultInstance());
      }
      /**
       * <code>repeated .tmindtech.protobuf.example.Example examples = 4;</code>
       */
      public java.util.List<com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder> 
           getExamplesBuilderList() {
        return getExamplesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tmindtech.api.model.protobuf.ExampleProtos.Example, com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder, com.tmindtech.api.model.protobuf.ExampleProtos.ExampleOrBuilder> 
          getExamplesFieldBuilder() {
        if (examplesBuilder_ == null) {
          examplesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tmindtech.api.model.protobuf.ExampleProtos.Example, com.tmindtech.api.model.protobuf.ExampleProtos.Example.Builder, com.tmindtech.api.model.protobuf.ExampleProtos.ExampleOrBuilder>(
                  examples_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          examples_ = null;
        }
        return examplesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tmindtech.protobuf.example.ExampleList)
    }

    // @@protoc_insertion_point(class_scope:tmindtech.protobuf.example.ExampleList)
    private static final com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList();
    }

    public static com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExampleList>
        PARSER = new com.google.protobuf.AbstractParser<ExampleList>() {
      public ExampleList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ExampleList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExampleList> getParserForType() {
      return PARSER;
    }

    public com.tmindtech.api.model.protobuf.ExampleProtos.ExampleList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddExampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tmindtech.protobuf.example.AddExample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 2;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string extras = 3;</code>
     */
    java.lang.String getExtras();
    /**
     * <code>string extras = 3;</code>
     */
    com.google.protobuf.ByteString
        getExtrasBytes();
  }
  /**
   * Protobuf type {@code tmindtech.protobuf.example.AddExample}
   */
  public  static final class AddExample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tmindtech.protobuf.example.AddExample)
      AddExampleOrBuilder {
    // Use AddExample.newBuilder() to construct.
    private AddExample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddExample() {
      name_ = "";
      description_ = "";
      extras_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_AddExample_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_AddExample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tmindtech.api.model.protobuf.ExampleProtos.AddExample.class, com.tmindtech.api.model.protobuf.ExampleProtos.AddExample.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 2;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRAS_FIELD_NUMBER = 3;
    private volatile java.lang.Object extras_;
    /**
     * <code>string extras = 3;</code>
     */
    public java.lang.String getExtras() {
      java.lang.Object ref = extras_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extras_ = s;
        return s;
      }
    }
    /**
     * <code>string extras = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExtrasBytes() {
      java.lang.Object ref = extras_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extras_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tmindtech.api.model.protobuf.ExampleProtos.AddExample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tmindtech.protobuf.example.AddExample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tmindtech.protobuf.example.AddExample)
        com.tmindtech.api.model.protobuf.ExampleProtos.AddExampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_AddExample_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_AddExample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tmindtech.api.model.protobuf.ExampleProtos.AddExample.class, com.tmindtech.api.model.protobuf.ExampleProtos.AddExample.Builder.class);
      }

      // Construct using com.tmindtech.api.model.protobuf.ExampleProtos.AddExample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        description_ = "";

        extras_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.internal_static_tmindtech_protobuf_example_AddExample_descriptor;
      }

      public com.tmindtech.api.model.protobuf.ExampleProtos.AddExample getDefaultInstanceForType() {
        return com.tmindtech.api.model.protobuf.ExampleProtos.AddExample.getDefaultInstance();
      }

      public com.tmindtech.api.model.protobuf.ExampleProtos.AddExample build() {
        com.tmindtech.api.model.protobuf.ExampleProtos.AddExample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tmindtech.api.model.protobuf.ExampleProtos.AddExample buildPartial() {
        com.tmindtech.api.model.protobuf.ExampleProtos.AddExample result = new com.tmindtech.api.model.protobuf.ExampleProtos.AddExample(this);
        result.name_ = name_;
        result.description_ = description_;
        result.extras_ = extras_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object extras_ = "";
      /**
       * <code>string extras = 3;</code>
       */
      public java.lang.String getExtras() {
        java.lang.Object ref = extras_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extras_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string extras = 3;</code>
       */
      public com.google.protobuf.ByteString
          getExtrasBytes() {
        java.lang.Object ref = extras_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extras_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extras = 3;</code>
       */
      public Builder setExtras(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extras_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extras = 3;</code>
       */
      public Builder clearExtras() {
        
        extras_ = getDefaultInstance().getExtras();
        onChanged();
        return this;
      }
      /**
       * <code>string extras = 3;</code>
       */
      public Builder setExtrasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extras_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tmindtech.protobuf.example.AddExample)
    }

    // @@protoc_insertion_point(class_scope:tmindtech.protobuf.example.AddExample)
    private static final com.tmindtech.api.model.protobuf.ExampleProtos.AddExample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tmindtech.api.model.protobuf.ExampleProtos.AddExample();
    }

    public static com.tmindtech.api.model.protobuf.ExampleProtos.AddExample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddExample>
        PARSER = new com.google.protobuf.AbstractParser<AddExample>() {
      public AddExample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(
                  builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AddExample> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddExample> getParserForType() {
      return PARSER;
    }

    public com.tmindtech.api.model.protobuf.ExampleProtos.AddExample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tmindtech_protobuf_example_Example_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tmindtech_protobuf_example_Example_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tmindtech_protobuf_example_ExampleList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tmindtech_protobuf_example_ExampleList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tmindtech_protobuf_example_AddExample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tmindtech_protobuf_example_AddExample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\032tmindtech.protobuf.exam" +
      "ple\032\037google/protobuf/timestamp.proto\"\252\001\n" +
      "\007Example\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\023\n\013de" +
      "scription\030\003 \001(\t\022\016\n\006extras\030\004 \001(\t\022/\n\013creat" +
      "e_time\030\005 \001(\0132\032.google.protobuf.Timestamp" +
      "\022/\n\013modify_time\030\006 \001(\0132\032.google.protobuf." +
      "Timestamp\"x\n\013ExampleList\022\016\n\006offset\030\001 \001(\005" +
      "\022\r\n\005count\030\002 \001(\005\022\023\n\013total_count\030\003 \001(\005\0225\n\010" +
      "examples\030\004 \003(\0132#.tmindtech.protobuf.exam" +
      "ple.Example\"?\n\nAddExample\022\014\n\004name\030\001 \001(\t\022",
      "\023\n\013description\030\002 \001(\t\022\016\n\006extras\030\003 \001(\tB3\n " +
      "com.tmindtech.api.model.protobufB\rExampl" +
      "eProtosH\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_tmindtech_protobuf_example_Example_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tmindtech_protobuf_example_Example_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tmindtech_protobuf_example_Example_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Extras", "CreateTime", "ModifyTime", });
    internal_static_tmindtech_protobuf_example_ExampleList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tmindtech_protobuf_example_ExampleList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tmindtech_protobuf_example_ExampleList_descriptor,
        new java.lang.String[] { "Offset", "Count", "TotalCount", "Examples", });
    internal_static_tmindtech_protobuf_example_AddExample_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tmindtech_protobuf_example_AddExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tmindtech_protobuf_example_AddExample_descriptor,
        new java.lang.String[] { "Name", "Description", "Extras", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
