CREATE TABLE t_example (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modify_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(200),
  extras TEXT
);